name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tools
        uses: asdf-vm/actions/install@v3

      - name: Setup dependencies
        run: |
          bundle install
          yarn install
          bundle exec rails assets:precompile

      - name: Run tests
        run: bundle exec rspec
